### ISSUE TITLE
Unuseable in a multithreaded contexts

### ISSUE THREAD

**Issue by fake-name** [alonho/pystuck#11]
Basically, if you have a multithreaded application (using real threads, e.g. the `multiprocessing` module), they all try to open the same port, and you get crashes.

Basically, it seems pystuck assumes it's installed into only one process. This is /probably/ not really something that can be fixed easily, given the current system architecture, but it's a good thing to note clearly in the documentation, if anything.

**Comment by fake-name** [comment]
A not-too-elegant-but-functional solution is to fiddle with the port:

```

def install_pystuck():
	import pystuck
	stuck_port = 6666
	while 1:
		try:
			pystuck.run_server(port=stuck_port)
			print("PyStuck installed to process, running on port %s" % stuck_port)
			break
		except OSError:
			stuck_port += 1
```

**Comment by alonho** [comment]
That's a general issue in multithreaded programs: using global resources like sockets or files should be handles carefully. That's why the general guideline is create them in the main thread before it spawns any other thread. (usually I put run_server at the first line of the main() of my programs!)

Also, you mentioned multiprocessing which supports both threads and processes. Forking into other processes would make it impossible to debug all children with a single server. It's untested and the results are undefined.. In that case perhaps you should explicitly pass a port to each child process.

**Comment by fake-name** [comment]
I think my issue is that python's "threads" aren't really *real* threads, whereas the "real" threads (e.g. multiprocessing) aren't called threads, and I have my head too far up c++ to be able to figure out which are meant from "dump all threads".

**Comment by fake-name** [comment]
s/multithreaded/multiprocessing/g

I've been doing too much c++. Bleh.
